### ISSUE TITLE
Implement pricing scheme for NFTs (rare/less rare NFTs)

### ISSUE THREAD

**Issue by Dobrokhvalov** [VolcaTech/cryptoxmas.xyz#44]
To make the app more engaging we would like to have some NFTs more rare that others (like Gitcoin Kudos). 

- More rare tokens should cost more. 
- The pricing logic should be implemented at the smart-contract level, so that it's not possible to cheat. 
- Bear in mind that other dapps can propose their own tokens with their own pricing logic.

**Comment by seichris** [comment]
@artyomignatyev yes. The minimal version of this, is to just show the price, as we already do. My preferred version is to also show the rarity (number of sold tokens) in the top left, like so:

![rarity](https://user-images.githubusercontent.com/25006584/49568749-32288f00-f932-11e8-94e0-3d8c5540470e.JPG)

**Comment by seichris** [comment]
There is two classes of NFTs: Rare tokens & unique tokens.

## Rare vs. Unique

**Rare:**
- Rare card NFTs are limited to different amounts
- Rare cards are priced in intervals from ~2 to ~100 USD

**Unique:**
- Each unique cards is one unique NFT
- Unique cards have an individual price, because
- Unique cards can have a special feature

### Naming & Pricing & Amounts 

**Rare:**
Common = 0.02 eth = 200
Special = 0.05 eth = 88
Rare = 0.1 eth = 50
Scarce = 0.2 eth = 33
Limited = 0.5 eth = 20
Epic = 1 eth = 10

**Unique:**
Unique = ? = 1 NFT

^ Everything still up for discussion. 

### UI

We start with a set different color combinations of one .svg.
- The top right shows the price.
- The top left shows the Rarity Level. On click, it shows the number of sold NFTs vs the total amount.
- The bottom shows the NFTs ID. i.e. if its the first minted NFT, it shows a '1'. (@artyomignatyev up for discussion)

![rare](https://user-images.githubusercontent.com/25006584/49579786-8b51ec00-f94d-11e8-8376-c11f9ff8d424.JPG)

We also need to explain the rarity somewhere in the UI. Like this:
![rarity explainer](https://user-images.githubusercontent.com/25006584/49580656-bd644d80-f94f-11e8-8fe8-66f762c11104.JPG)

**Open questions:**
- What to show, if an NFT is sold out? Gray it out, completely delete it from UI, or have its own section.
- How do we show the special feature in the UI? Maybe a glow around the box. It also needs a popup explainer, or its own screen.


## Technical details

- There will be different NFT contracts. E.g. for now that is our and the Kudos one.
- Set pricing for a range of tokens. E.g. in range 0-100 costs 0.05ETH, 101-200 - 0.1ETH etc.
- We will mint 500 tokens, e.g. with IDs from 1,2,4,... to 60 & from 101,… to 160 etc.
So we will be able to mint tokens in range from 60 to 100, 160-200, etc after
- add PricingContract for each NFT contract. The pricing contract will have **default price for rare tokens** and can contain **mapping for unique ones**.

**Comment by seichris** [comment]
@Dobrokhvalov proposed to raise the minimum price to 0.1 eth.

What is your take @artyomignatyev @Kisgus ?

**Comment by seichris** [comment]
Update. We cut _Common_ and set 100 pieces for _Special_:

Special = 0.05 eth = 100 pieces
Rare = 0.1 eth = 50
Scarce = 0.2 eth = 33
Limited = 0.5 eth = 20
Epic = 1 eth = 10

@sashamihaha we need to update this in the UI. I updated it in the figma

I will prepare a pricing sheet.

**Comment by Dobrokhvalov** [comment]
Implemented in https://github.com/VolcaTech/cryptoxmas.xyz/pull/79
