### ISSUE TITLE
Postpone Metamask integration

### ISSUE THREAD

**Issue by Kisgus** [VolcaTech/cryptoxmas.xyz#61]
# This is a ✨ [Cryptoxmas.xyz](https://cryptoxmas.xyz/) bounty✨
**Every bounty DAI paid out will be matched as a donation to this** [Venezuelan Giveth Campaign](https://release.giveth.io/campaigns/5c05357a4a1382778fc07cef)

## Userstory

**As a user I want to be able to** view Christmas Cards before being asked to login via metamask,
**so that I can** see the selection of images from a normal web2 browser.

## Requires

- web3.js -> ethers.js migration as in #31  

## UI 

Will be proposed by @seichris & @artyomignatyev

**Comment by seichris** [comment]
Same issue as this one https://github.com/VolcaTech/cryptoxmas.xyz/issues/31

**Comment by Dobrokhvalov** [comment]
They have different scopes. This one postpones connection to Metamask, #31 is for changing js libraries.  
#31 is purely technical, doesn't have updates to the UI. 
Having #31 implemented, we can start working on this one.

**Comment by seichris** [comment]
So, in the UI there is 3 states, we have to "postpone" then.

### Loading, because not signed

Right now:
[screenshot]

Postpone to "buy & send" screen. How should it look like?

### No Metamask installed

Right now:
[screenshot]

Postpone to "buy & send" screen? Full screen or popup or...?

Fixes:
- Gray text under button: "Metamask addon for Chrome, Firefox"

### Wrong network

Right now:
[screenshot]

Postpone to "buy & send" screen? Full screen or popup or...?

**Comment by danfinlay** [comment]
FYI, you don't need to ask a user to open MetaMask to log in anymore, thanks to the new method `ethereum.enable()`:
https://medium.com/metamask/eip-1102-preparing-your-dapp-5027b2c9ed76

**Comment by seichris** [comment]
Thanks for the reminder @danfinlay . We are using `ethereum.enable()` already and hope we can update the UX on this flow in this issue, so web2 users actually can surf our NFTs.

@artyomignatyev i updated the figma screenshots above.
